/**
 * TypeScript Type Definitions
 * 
 * This file defines all core data models and interfaces for the YouTube Subtitle Enhancer extension.
 * Based on data-model.md v1.0.0
 * 
 * @author YouTube Subtitle Enhancer Team
 * @since 0.1.0
 */

// ============================================================================
// User Configuration
// ============================================================================

/**
 * Word entry in user's vocabulary list
 */
export interface WordEntry {
  /** Word in lowercase form */
  word: string;
  /** Lemma (root form) for word variation matching */
  lemma?: string;
  /** Timestamp when word was added (milliseconds) */
  addedTime: number;
  /** Source of the word addition */
  source?: 'manual' | 'interactive' | 'level';
}

/**
 * User profile containing settings and vocabulary
 * Stored in chrome.storage.local under 'user_profile' key
 */
export interface UserProfile {
  // English proficiency level
  /** User's English proficiency level */
  englishLevel: 'beginner' | 'intermediate' | 'advanced';

  // LLM API configuration
  /** LLM service provider */
  llmProvider: 'openai' | 'claude' | 'deepseek';
  /** User's LLM API key */
  llmApiKey: string;
  /** Optional: specific model to use (defaults: gpt-4o-mini / claude-3-5-haiku / deepseek-chat) */
  llmModel?: string;

  // Vocabulary lists
  /** Words the user has mastered */
  masteredWords: WordEntry[];
  /** Words the user wants to focus on learning */
  focusWords: WordEntry[];

  /** Words from level-based dictionary that the user doesn't want to see in mastered list */
  ignoredLevelWords?: string[];
  
  // UI preferences
  /** Subtitle font size in pixels (default: 16) */
  subtitleFontSize: number;
  /** Subtitle text color (default: '#ffffff') */
  subtitleFontColor: string;
  /** Subtitle background color (default: 'rgba(0,0,0,0.8)') */
  subtitleBackgroundColor: string;
  /** Translation text color (default: '#ffeb3b') */
  translationColor: string;

  // Extension state
  /** Extension master toggle (default: true) */
  isEnabled: boolean;
  /** Whether to show onboarding guide (default: true) */
  showOnboardingGuide: boolean;

  // Statistics (optional)
  /** Total number of videos watched with enhanced subtitles */
  totalVideosWatched?: number;
  /** Total number of words learned */
  totalWordsLearned?: number;
  /** Timestamp of first installation */
  createdAt: number;
  /** Timestamp of last extension usage */
  lastUsedAt: number;
}

// ============================================================================
// Subtitle Processing
// ============================================================================

/**
 * Analysis of a single word in subtitle text
 */
export interface WordAnalysis {
  /** Word in its original form */
  word: string;
  /** Lemma (root form) of the word */
  lemma: string;
  /** Whether this word is unknown to the user */
  isUnknown: boolean;
  /** LLM-generated Chinese translation (if unknown) */
  translation?: string;
  /** Position in the original text */
  position: {
    /** Start character index */
    start: number;
    /** End character index */
    end: number;
  };
  /** Difficulty level of the word */
  difficulty?: 'beginner' | 'intermediate' | 'advanced' | 'expert';
}

/**
 * A single subtitle segment with timing and enhanced content
 */
export interface SubtitleSegment {
  // Timing
  /** Start time in seconds */
  startTime: number;
  /** End time in seconds */
  endTime: number;

  // Text content
  /** Original English subtitle text */
  originalText: string;
  /** Enhanced HTML with inline translations */
  enhancedHTML: string;

  // Word analysis
  /** Analysis of each word in the segment */
  words: WordAnalysis[];
}

/**
 * Video session tracking current or cached video state
 * Stored in chrome.storage.local under 'video_cache_${videoId}' key
 */
export interface VideoSession {
  // Video identification
  /** YouTube video ID */
  videoId: string;
  /** Video title (optional) */
  videoTitle?: string;

  // Subtitle data
  /** Subtitle language code (e.g., 'en') */
  subtitleLanguage: string;
  /** Subtitle API URL */
  subtitleTrackUrl: string;
  /** Whether subtitles are auto-generated */
  isAutoGenerated: boolean;
  /** All subtitle segments */
  segments: SubtitleSegment[];

  // Processing state
  /** Whether subtitle processing is in progress */
  isProcessing: boolean;
  /** Processing progress (0-100) */
  processingProgress: number;
  /** Timestamp of last processing */
  lastProcessedTime: number;

  // Cache metadata
  /** Cache expiry timestamp (7 days) */
  cacheExpiry: number;
}

/**
 * Caption track information
 * Used for fetching subtitles from YouTube
 */
export interface CaptionTrack {
  /** Language code (e.g., 'en', 'zh-Hans') */
  languageCode: string;
  /** Language name (e.g., 'English', '中文（简体）') */
  name: string;
  /** Whether this is auto-generated (ASR) captions */
  isAutoGenerated: boolean;
}

// ============================================================================
// Translation Cache
// ============================================================================

/**
 * Cached LLM translation result
 * Stored in chrome.storage.local under 'translation_cache_${contextHash}' key
 */
export interface TranslationCacheEntry {
  /** Word being translated */
  word: string;
  /** Context snippet (first 50 characters) */
  context: string;
  /** Hash of word + context for quick lookup */
  contextHash: string;
  /** LLM-generated Chinese translation */
  translation: string;
  /** Cache creation timestamp */
  timestamp: number;
  /** Cache expiry timestamp (7 days) */
  expiryTime: number;
  /** LLM provider used */
  llmProvider: 'openai' | 'claude' | 'deepseek';
  /** LLM model used */
  llmModel: string;
}

// ============================================================================
// CSV Export/Import
// ============================================================================

/**
 * CSV row format for vocabulary export/import
 */
export interface CSVRow {
  /** Vocabulary type */
  type: 'mastered' | 'focus';
  /** Word in lowercase */
  word: string;
  /** Timestamp as string (needs conversion to number) */
  addedTime: string;
}

/**
 * Data structure for CSV export
 */
export interface CSVExportData {
  /** Mastered words list */
  masteredWords: WordEntry[];
  /** Focus words list */
  focusWords: WordEntry[];
}

// ============================================================================
// Message Passing (Content Script ↔ Service Worker)
// ============================================================================

/**
 * Message types for communication between content script and service worker
 */
export enum MessageType {
  // Subtitle operations
  GET_SUBTITLE = 'GET_SUBTITLE',
  SUBTITLE_RESPONSE = 'SUBTITLE_RESPONSE',

  // Translation operations
  TRANSLATE_WORDS = 'TRANSLATE_WORDS',
  TRANSLATION_RESPONSE = 'TRANSLATION_RESPONSE',

  // Vocabulary operations
  ADD_MASTERED_WORD = 'ADD_MASTERED_WORD',
  REMOVE_MASTERED_WORD = 'REMOVE_MASTERED_WORD',
  ADD_FOCUS_WORD = 'ADD_FOCUS_WORD',
  REMOVE_FOCUS_WORD = 'REMOVE_FOCUS_WORD',
  CHECK_WORD_STATUS = 'CHECK_WORD_STATUS',
  WORD_STATUS_RESPONSE = 'WORD_STATUS_RESPONSE',

  // Configuration operations
  GET_USER_PROFILE = 'GET_USER_PROFILE',
  USER_PROFILE_RESPONSE = 'USER_PROFILE_RESPONSE',
  UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE',

  // Video operations
  VIDEO_CHANGED = 'VIDEO_CHANGED',
  VIDEO_SESSION_UPDATE = 'VIDEO_SESSION_UPDATE',

  // Cache/Fetch status
  CACHE_MISS = 'CACHE_MISS',
  
  // Error handling
  ERROR = 'ERROR',
}

/**
 * Base message structure
 */
export interface BaseMessage {
  /** Message type identifier */
  type: MessageType;
  /** Optional request ID for response matching */
  requestId?: string;
}

/**
 * Request to get subtitle for a video
 */
export interface GetSubtitleMessage extends BaseMessage {
  type: MessageType.GET_SUBTITLE;
  /** YouTube video ID */
  videoId: string;
  /** Optional subtitle language preference */
  language?: string;
}

/**
 * Response with subtitle data
 */
export interface SubtitleResponseMessage extends BaseMessage {
  type: MessageType.SUBTITLE_RESPONSE;
  /** Video session data */
  session: VideoSession;
  /** Whether data was from cache */
  fromCache: boolean;
}

/**
 * Request to translate words
 */
export interface TranslateWordsMessage extends BaseMessage {
  type: MessageType.TRANSLATE_WORDS;
  /** Words to translate with context */
  words: Array<{
    word: string;
    context: string;
  }>;
}

/**
 * Response with translations
 */
export interface TranslationResponseMessage extends BaseMessage {
  type: MessageType.TRANSLATION_RESPONSE;
  /** Translations for each word */
  translations: Array<{
    word: string;
    translation: string;
  }>;
}

/**
 * Request to add word to mastered list
 */
export interface AddMasteredWordMessage extends BaseMessage {
  type: MessageType.ADD_MASTERED_WORD;
  /** Word to add */
  word: string;
  /** Optional lemma */
  lemma?: string;
  /** Source of addition */
  source?: 'manual' | 'interactive';
}

/**
 * Request to get user profile
 */
export interface GetUserProfileMessage extends BaseMessage {
  type: MessageType.GET_USER_PROFILE;
}

/**
 * Response with user profile
 */
export interface UserProfileResponseMessage extends BaseMessage {
  type: MessageType.USER_PROFILE_RESPONSE;
  /** User profile data */
  profile: UserProfile;
}

/**
 * Error message
 */
export interface ErrorMessage extends BaseMessage {
  type: MessageType.ERROR;
  /** Error message */
  error: string;
  /** Optional error code */
  code?: string;
}

/**
 * Union type of all possible messages
 */
export type Message =
  | GetSubtitleMessage
  | SubtitleResponseMessage
  | TranslateWordsMessage
  | TranslationResponseMessage
  | AddMasteredWordMessage
  | GetUserProfileMessage
  | UserProfileResponseMessage
  | ErrorMessage;

// ============================================================================
// Storage Keys
// ============================================================================

/**
 * Storage key constants
 */
export const StorageKeys = {
  USER_PROFILE: 'user_profile',
  DATA_VERSION: 'data_version',
  VIDEO_CACHE_PREFIX: 'video_cache_',
  TRANSLATION_CACHE_PREFIX: 'translation_cache_',
} as const;

// ============================================================================
// Constants
// ============================================================================

/**
 * Cache expiry duration (7 days in milliseconds)
 */
export const CACHE_EXPIRY_MS = 7 * 24 * 60 * 60 * 1000;

/**
 * Storage quota constants
 */
export const STORAGE_QUOTA_BYTES = 10 * 1024 * 1024; // 10 MB
export const STORAGE_WARNING_THRESHOLD = 0.8; // 80%

/**
 * Current data model version
 */
export const CURRENT_DATA_VERSION = '1.0.0';

/**
 * Default user profile
 */
export const defaultUserProfile: UserProfile = {
  englishLevel: 'intermediate',
  llmProvider: 'deepseek',
  llmApiKey: '',
  llmModel: 'deepseek-chat', // DeepSeek default model
  masteredWords: [],
  focusWords: [],
  subtitleFontSize: 16,
  subtitleFontColor: '#ffffff',
  subtitleBackgroundColor: 'rgba(0,0,0,0.8)',
  translationColor: '#00ff00',
  isEnabled: true,
  showOnboardingGuide: true,
  createdAt: Date.now(),
  lastUsedAt: Date.now(),
};
