/**
 * Test script for YouTube Subtitle Extractor V2
 * 
 * Run this in browser console on a YouTube video page to test
 * the subtitle extraction functionality.
 * 
 * Usage:
 * 1. Open a YouTube video page
 * 2. Open browser console (F12)
 * 3. Copy and paste this script
 * 4. Run testSubtitleExtraction()
 */

import { 
  extractCaptionTracks, 
  findEnglishTrack, 
  downloadSubtitleData,
  parseJSON3Subtitle,
  extractEnglishSubtitles 
} from './youtube-subtitle-extractor-v2';

/**
 * Test the subtitle extraction pipeline
 */
export async function testSubtitleExtraction() {
  console.log('='.repeat(60));
  console.log('TESTING YOUTUBE SUBTITLE EXTRACTOR V2');
  console.log('='.repeat(60));
  
  try {
    // Extract video ID from URL
    const urlParams = new URLSearchParams(window.location.search);
    const videoId = urlParams.get('v');
    
    if (!videoId) {
      console.error('❌ Not on a YouTube video page');
      return;
    }
    
    console.log('Video ID:', videoId);
    console.log('');
    
    // Test Step 1: Extract caption tracks
    console.log('STEP 1: Extracting caption tracks...');
    const tracks = extractCaptionTracks();
    
    if (tracks.length === 0) {
      console.error('❌ No caption tracks found');
      return;
    }
    
    console.log(`✓ Found ${tracks.length} tracks:`);
    tracks.forEach((track, i) => {
      console.log(`  [${i}] ${track.languageCode} - ${track.name} (${track.isAutoGenerated ? 'auto' : 'manual'})`);
    });
    console.log('');
    
    // Test Step 2: Find English track
    console.log('STEP 2: Finding English track...');
    const englishTrack = findEnglishTrack(tracks);
    
    if (!englishTrack) {
      console.error('❌ No English track found');
      return;
    }
    
    console.log('✓ Selected English track:');
    console.log('  Language:', englishTrack.languageCode);
    console.log('  Name:', englishTrack.name);
    console.log('  Auto-generated:', englishTrack.isAutoGenerated);
    console.log('  Base URL:', englishTrack.baseUrl.substring(0, 100) + '...');
    console.log('');
    
    // Test Step 3: Download subtitle data
    console.log('STEP 3: Downloading subtitle data...');
    const subtitleData = await downloadSubtitleData(englishTrack.baseUrl);
    console.log('✓ Downloaded', subtitleData.length, 'bytes');
    console.log('  Preview:', subtitleData.substring(0, 200) + '...');
    console.log('');
    
    // Test Step 4: Parse subtitle data
    console.log('STEP 4: Parsing subtitle data...');
    const segments = parseJSON3Subtitle(subtitleData);
    console.log(`✓ Parsed ${segments.length} segments`);
    console.log('');
    
    // Display sample segments
    console.log('SAMPLE SEGMENTS:');
    segments.slice(0, 5).forEach((seg, i) => {
      console.log(`  [${i}] ${seg.startTime.toFixed(2)}s - ${seg.endTime.toFixed(2)}s`);
      console.log(`      "${seg.originalText}"`);
    });
    console.log('');
    
    console.log('='.repeat(60));
    console.log('✓ ALL TESTS PASSED');
    console.log('='.repeat(60));
    
    return segments;
  } catch (error) {
    console.error('='.repeat(60));
    console.error('❌ TEST FAILED');
    console.error('='.repeat(60));
    console.error('Error:', error);
    console.error('Stack:', (error as Error).stack);
    throw error;
  }
}

/**
 * Quick test using the all-in-one function
 */
export async function quickTest() {
  const urlParams = new URLSearchParams(window.location.search);
  const videoId = urlParams.get('v');
  
  if (!videoId) {
    console.error('Not on a YouTube video page');
    return;
  }
  
  console.log('Quick test for video:', videoId);
  
  try {
    const segments = await extractEnglishSubtitles(videoId);
    console.log(`✓ Success! Got ${segments.length} segments`);
    console.log('First 3 segments:');
    segments.slice(0, 3).forEach(s => {
      console.log(`  ${s.startTime}s: ${s.originalText}`);
    });
    return segments;
  } catch (error) {
    console.error('❌ Failed:', error);
    throw error;
  }
}

// Auto-run test if in browser environment
if (typeof window !== 'undefined') {
  console.log('Subtitle Extractor V2 Test loaded!');
  console.log('Run: testSubtitleExtraction() or quickTest()');
  
  // Expose to window for easy testing
  (window as any).testSubtitleExtraction = testSubtitleExtraction;
  (window as any).quickTest = quickTest;
}
