/**
 * YouTube Subtitle Extractor V2
 * 
 * Improved implementation based on yt-dlp's approach
 * This version focuses on reliable extraction from ytInitialPlayerResponse
 * and proper subtitle download with correct headers and parameters.
 * 
 * @module content/youtube-subtitle-extractor-v2
 * @author YouTube Subtitle Enhancer Team
 * @since 0.2.0
 */

import type { SubtitleSegment } from '../types/index';

/**
 * Caption track information
 */
export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
  kind?: string;
}

/**
 * JSON3 subtitle format (YouTube's internal format)
 */
interface JSON3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: Array<{
    utf8?: string;
    tOffsetMs?: number;
  }>;
}

interface JSON3Response {
  events?: JSON3Event[];
}

/**
 * Extract ytInitialPlayerResponse from the page
 * Tries multiple methods to ensure we get the data
 */
function extractYtInitialPlayerResponse(): any {
  console.log('=== Extracting ytInitialPlayerResponse ===');
  
  const win = window as any;
  
  // Method 1: Direct access from window object
  if (win.ytInitialPlayerResponse) {
    console.log('✓ Found ytInitialPlayerResponse in window object');
    return win.ytInitialPlayerResponse;
  }
  
  // Method 2: Search in script tags
  console.log('Searching in script tags...');
  const scripts = document.querySelectorAll('script');
  
  for (const script of scripts) {
    const content = script.textContent || '';
    if (!content.includes('ytInitialPlayerResponse')) {
      continue;
    }
    
    // Try multiple patterns
    const patterns = [
      /var ytInitialPlayerResponse\s*=\s*({.+?});/s,
      /ytInitialPlayerResponse\s*=\s*({.+?});/s,
      /window\["ytInitialPlayerResponse"\]\s*=\s*({.+?});/s,
      /window\.ytInitialPlayerResponse\s*=\s*({.+?});/s,
    ];
    
    for (const pattern of patterns) {
      const match = content.match(pattern);
      if (match && match[1]) {
        try {
          // Try to parse the JSON
          const jsonStr = match[1];
          const response = JSON.parse(jsonStr);
          console.log('✓ Found ytInitialPlayerResponse in script tag');
          return response;
        } catch (parseError) {
          console.warn('Failed to parse JSON from script tag:', parseError);
          continue;
        }
      }
    }
  }
  
  // Method 3: Try to extract from ytcfg
  if (win.ytcfg?.data_) {
    console.log('Checking ytcfg.data_...');
    // Sometimes player response is stored elsewhere
    if (win.ytcfg.data_.PLAYER_RESPONSE) {
      console.log('✓ Found PLAYER_RESPONSE in ytcfg');
      return win.ytcfg.data_.PLAYER_RESPONSE;
    }
  }
  
  console.error('❌ Could not find ytInitialPlayerResponse');
  return null;
}

/**
 * Extract caption tracks from player response
 */
export function extractCaptionTracks(playerResponse?: any): CaptionTrack[] {
  try {
    // If no player response provided, extract from page
    const response = playerResponse || extractYtInitialPlayerResponse();
    
    if (!response) {
      console.error('No player response available');
      return [];
    }
    
    console.log('=== Extracting caption tracks from player response ===');
    
    // Navigate the response structure
    const captions = response.captions;
    if (!captions) {
      console.warn('No captions object in player response');
      console.log('Player response keys:', Object.keys(response));
      return [];
    }
    
    const renderer = 
      captions.playerCaptionsTracklistRenderer ||
      captions.playerCaptionsRenderer?.playerCaptionsTracklistRenderer;
    
    if (!renderer) {
      console.warn('No playerCaptionsTracklistRenderer found');
      console.log('Captions keys:', Object.keys(captions));
      return [];
    }
    
    const tracks = renderer.captionTracks || [];
    console.log(`Found ${tracks.length} caption tracks`);
    
    if (tracks.length > 0) {
      console.log('First track sample:', {
        languageCode: tracks[0].languageCode,
        name: tracks[0].name?.simpleText,
        kind: tracks[0].kind,
        hasBaseUrl: !!tracks[0].baseUrl,
      });
    }
    
    return tracks.map((track: any) => ({
      baseUrl: track.baseUrl,
      languageCode: track.languageCode || '',
      name: track.name?.simpleText || track.name?.runs?.[0]?.text || track.languageCode || '',
      isAutoGenerated: track.kind === 'asr',
      kind: track.kind,
    }));
  } catch (error) {
    console.error('Failed to extract caption tracks:', error);
    return [];
  }
}

/**
 * Find the best English caption track
 */
export function findEnglishTrack(tracks: CaptionTrack[]): CaptionTrack | null {
  if (!tracks || tracks.length === 0) {
    console.warn('No tracks provided');
    return null;
  }
  
  console.log('Finding best English track from', tracks.length, 'tracks');
  console.log('Available languages:', tracks.map(t => t.languageCode).join(', '));
  
  // Priority 1: Manual English track
  const manualEn = tracks.find(t => t.languageCode === 'en' && !t.isAutoGenerated);
  if (manualEn) {
    console.log('✓ Found manual English track');
    return manualEn;
  }
  
  // Priority 2: Auto-generated English track
  const autoEn = tracks.find(t => t.languageCode === 'en' && t.isAutoGenerated);
  if (autoEn) {
    console.log('✓ Found auto-generated English track');
    return autoEn;
  }
  
  // Priority 3: Any English variant (en-US, en-GB, etc.)
  const anyEn = tracks.find(t => t.languageCode.startsWith('en'));
  if (anyEn) {
    console.log('✓ Found English variant:', anyEn.languageCode);
    return anyEn;
  }
  
  console.warn('❌ No English track found');
  return null;
}

/**
 * Download subtitle data from YouTube
 * Uses proper headers and parameters based on yt-dlp's implementation
 */
export async function downloadSubtitleData(baseUrl: string): Promise<string> {
  try {
    console.log('=== Downloading subtitle ===');
    console.log('Base URL:', baseUrl.substring(0, 100) + '...');
    
    // Parse and modify URL
    const url = new URL(baseUrl);
    
    // Set format to json3 (YouTube's structured format)
    url.searchParams.set('fmt', 'json3');
    
    // Disable text position data (as yt-dlp does)
    // This prevents undesirable formatting in VTT/JSON3 formats
    url.searchParams.delete('xosf');
    
    const finalUrl = url.toString();
    console.log('Final URL:', finalUrl.substring(0, 150) + '...');
    
    // Make request with proper headers
    // Important: This must run in content script context to access cookies
    const response = await fetch(finalUrl, {
      method: 'GET',
      headers: {
        'Accept': 'application/json, text/plain, */*',
        'Accept-Language': 'en-US,en;q=0.9',
        'Origin': 'https://www.youtube.com',
        'Referer': window.location.href,
        'User-Agent': navigator.userAgent,
      },
      credentials: 'include', // Critical: include cookies
      cache: 'default',
    });
    
    console.log('Response status:', response.status);
    console.log('Response headers:', {
      contentType: response.headers.get('content-type'),
      contentLength: response.headers.get('content-length'),
    });
    
    if (!response.ok) {
      const errorText = await response.text().catch(() => 'Unable to read error');
      console.error('Response error:', errorText);
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }
    
    const text = await response.text();
    console.log('Response length:', text.length);
    
    if (!text || text.trim().length === 0) {
      throw new Error('Empty response from YouTube');
    }
    
    // Verify it's valid JSON
    try {
      JSON.parse(text);
      console.log('✓ Valid JSON response');
    } catch (parseError) {
      console.error('Response is not valid JSON:', text.substring(0, 200));
      throw new Error('Invalid JSON response from YouTube');
    }
    
    console.log('✓ Subtitle downloaded successfully');
    return text;
  } catch (error) {
    console.error('Failed to download subtitle:', error);
    throw error;
  }
}

/**
 * Parse JSON3 format subtitle data
 */
export function parseJSON3Subtitle(json3Data: string): SubtitleSegment[] {
  try {
    console.log('=== Parsing JSON3 subtitle ===');
    
    const data: JSON3Response = JSON.parse(json3Data);
    
    if (!data.events || !Array.isArray(data.events)) {
      console.error('Invalid JSON3 format: no events array');
      console.log('Data keys:', Object.keys(data));
      throw new Error('Invalid JSON3 format');
    }
    
    console.log('Total events:', data.events.length);
    
    const segments: SubtitleSegment[] = [];
    
    for (const event of data.events) {
      // Skip events without text
      if (!event.segs || event.segs.length === 0) {
        continue;
      }
      
      const startTime = (event.tStartMs || 0) / 1000;
      const duration = (event.dDurationMs || 0) / 1000;
      const endTime = startTime + duration;
      
      // Combine text segments
      const text = event.segs
        .map(seg => seg.utf8 || '')
        .join('')
        .trim();
      
      if (!text) {
        continue;
      }
      
      segments.push({
        startTime,
        endTime,
        originalText: text,
        enhancedHTML: '', // Will be filled by processor
        words: [], // Will be filled by processor
      });
    }
    
    console.log(`✓ Parsed ${segments.length} subtitle segments`);
    
    if (segments.length > 0) {
      console.log('Sample segments:');
      segments.slice(0, 3).forEach((seg, i) => {
        console.log(`  [${i}] ${seg.startTime.toFixed(2)}s: "${seg.originalText.substring(0, 50)}..."`);
      });
    }
    
    return segments;
  } catch (error) {
    console.error('Failed to parse JSON3 subtitle:', error);
    throw error;
  }
}

/**
 * Main function: Extract English subtitles for a YouTube video
 */
export async function extractEnglishSubtitles(videoId: string): Promise<SubtitleSegment[]> {
  console.log('=== Extracting English subtitles ===');
  console.log('Video ID:', videoId);
  
  try {
    // Step 1: Get player response
    const playerResponse = extractYtInitialPlayerResponse();
    if (!playerResponse) {
      throw new Error('Could not get player response from page');
    }
    
    // Step 2: Extract caption tracks
    const tracks = extractCaptionTracks(playerResponse);
    if (tracks.length === 0) {
      throw new Error('No caption tracks found');
    }
    
    // Step 3: Find English track
    const englishTrack = findEnglishTrack(tracks);
    if (!englishTrack) {
      throw new Error('No English subtitle track found');
    }
    
    console.log('Selected track:', {
      language: englishTrack.languageCode,
      name: englishTrack.name,
      isAuto: englishTrack.isAutoGenerated,
    });
    
    // Step 4: Download subtitle data
    const subtitleData = await downloadSubtitleData(englishTrack.baseUrl);
    
    // Step 5: Parse subtitle data
    const segments = parseJSON3Subtitle(subtitleData);
    
    if (segments.length === 0) {
      throw new Error('No subtitle segments found after parsing');
    }
    
    console.log('✓ Successfully extracted subtitles');
    return segments;
  } catch (error) {
    console.error('Failed to extract English subtitles:', error);
    throw error;
  }
}
