#!/usr/bin/env node
/**
 * Inject environment variables into extension configuration
 * 
 * This script reads API keys from environment variables and creates
 * a config file that will be bundled with the extension.
 * 
 * Usage:
 *   node scripts/inject-env.js
 *   OPENAI_API_KEY=xxx npm run dev
 */

const fs = require('fs');
const path = require('path');

// Read environment variables
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || '';
const CLAUDE_API_KEY = process.env.CLAUDE_API_KEY || '';
const LLM_PROVIDER = process.env.LLM_PROVIDER || 'deepseek';
const LLM_MODEL = process.env.LLM_MODEL || 'deepseek-chat';

// Determine which API key to use based on provider
let apiKey = '';
if (LLM_PROVIDER === 'deepseek' || LLM_PROVIDER === 'openai') {
  apiKey = OPENAI_API_KEY;
} else if (LLM_PROVIDER === 'claude') {
  apiKey = CLAUDE_API_KEY;
}

// Create config content
const configContent = `/**
 * Environment Configuration
 * 
 * This file is auto-generated by scripts/inject-env.js
 * DO NOT EDIT MANUALLY
 * 
 * To update, set environment variables and run:
 *   npm run inject-env
 */

export const ENV_CONFIG = {
  LLM_PROVIDER: '${LLM_PROVIDER}',
  LLM_API_KEY: '${apiKey}',
  LLM_MODEL: '${LLM_MODEL}',
} as const;

export const HAS_API_KEY = ${apiKey.length > 0};
`;

// Write to src/config/env.ts
const configDir = path.join(__dirname, '../src/config');
const configFile = path.join(configDir, 'env.ts');

// Create directory if it doesn't exist
if (!fs.existsSync(configDir)) {
  fs.mkdirSync(configDir, { recursive: true });
}

// Write config file
fs.writeFileSync(configFile, configContent, 'utf-8');

console.log('✓ Environment configuration injected');
console.log(`  Provider: ${LLM_PROVIDER}`);
console.log(`  Model: ${LLM_MODEL}`);
console.log(`  API Key: ${apiKey ? '***' + apiKey.slice(-4) : '(not set)'}`);

if (!apiKey) {
  console.warn('\n⚠️  Warning: No API key found in environment variables');
  console.warn('   Set OPENAI_API_KEY in your .env file or environment');
  console.warn('   Example: OPENAI_API_KEY=your_key npm run dev');
}
